### ISSUE TITLE
Is there a place to download updated windows binaries, including zbarimg ?

### ISSUE THREAD

**Issue by Ortega-Dan** [mchehab/zbar#125]

**Comment by mchehab** [comment]
Yes, since this weekend :-)

The binaries for versions 0.23.90 and 0.23.91 are at:
   https://linuxtv.org/downloads/zbar/binaries/

PS.: Both versions should be identical, except for the version number. The only difference between those two releases were the code that generate the binaries: at version 0.23.91, the Linux binaries were generated against Ubuntu 20.04, instead of Debian SID, and they have the right version number on it.

**Comment by Ortega-Dan** [comment]
Good. Thank you very much. This results very useful.
