### ISSUE TITLE
Unable to detect code128

### ISSUE THREAD

**Issue by kratsg** [mchehab/zbar#127]
Hi, I have an image that I post-processed to extract out the bar code (and pad it) to make it easier for zbar to handle, however it's unable to identify a barcode.

![2S7A0004](https://user-images.githubusercontent.com/761483/98427928-35bc7780-206d-11eb-8c26-f4520081916b.JPG)

I start with the above image and post-process to the following

![step6](https://user-images.githubusercontent.com/761483/98427953-440a9380-206d-11eb-8e97-e57c706a32c6.jpg)

yet zbar is unable to identify this

```
$ zbarimg -Scode128.enable step6.jpg 
scanned 0 barcode symbols from 1 images in 0.42 seconds


WARNING: barcode data was not detected in some image(s)
Things to check:
  - is the barcode type supported? Currently supported symbologies are:
	. EAN/UPC (EAN-13, EAN-8, EAN-2, EAN-5, UPC-A, UPC-E, ISBN-10, ISBN-13)
	. DataBar, DataBar Expanded
	. Code 128
	. Code 93
	. Code 39
	. Codabar
	. Interleaved 2 of 5
	. QR code
	. SQ code
  - is the barcode large enough in the image?
  - is the barcode mostly in focus?
  - is there sufficient contrast/illumination?
  - If the symbol is split in several barcodes, are they combined in one image?
  - Did you enable the barcode type?
    some EAN/UPC codes are disabled by default. To enable all, use:
    $ zbarimg -S*.enable <files>
    Please also notice that some variants take precedence over others.
    Due to that, if you want, for example, ISBN-10, you should do:
    $ zbarimg -Sisbn10.enable <files>
```

any suggestions? it cannot find the barcode in the original image either.

**Comment by michaeltandy** [comment]
Here's your barcode compared to a vector barcode with the same content, generated by `python-barcode`

![barcode comparison image](https://user-images.githubusercontent.com/2449410/111842949-2d682900-88f8-11eb-9714-2ea5ce9e44e7.png)

Look at the narrow black bars above the letter G in your barcode - in my vector version, the two bars are the same width, while in your printed barcode the right one is about twice as wide as the left one.

I'm guessing this barcode is on a pretty small label - small enough that the narrowest bars are perhaps 1.75 printer pixels wide. Sometimes your printer rounds them up to 2 printer pixels, other times they get rounded down to 1 printer pixel.

Some barcode scanners would handle this - but that's because they're generously correcting for a badly printed barcode. If you want to read it with zbar then print it bigger, reduce the number of characters in the same space, or get a higher resolution printer.

**Comment by kratsg** [comment]
Thanks!
