### ISSUE TITLE
confirm the latest release

### ISSUE THREAD

**Issue by chenrui333** [mchehab/zbar#157]
👋  it looks like the most recent release `0.23.91` is using a big different number than the last one, `0.23.1`, raising this issue to double confirm the intention. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/71242

**Comment by mchehab** [comment]
(copying the same message I added at Homebrew/homebrew-core#71242)

It should be OK to use zbar-0.23.90, as the main changes from 0.23.1 are bug fixes.

That's said, I'm using major.minor.9x for test releases. In this specific case, what I'm testing is to use Github's actions, instead of Travis CI. One of the actions generates a per-OS set of binary files that can only be generated when a new release is trigged. That's due to two reasons:

    the trigger for such action is on: release
    it depends on the github.event.release.upload_url

While I don't see a way to override this limitation, I'll need to generate a couple of releases. So, you may expect some other 0.23.9x releases soon. Once everything is OK with Github's actions, I'll release version 0.24.0.
